version: "3"

services:
  fab:
    image: rpi:1.0
    build: .
    volumes:
      - .:/home
    # entrypoint: sh -c 'jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --notebook-dir=/home --allow-root'

